name: 05 - 2 - Event Filters and Activity Types
on:
  workflow_dispatch:
# on:
#   pull_request:
#     types:
#       - closed
#     branches:
#       - main
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running whenever a PR is closed"
